@startuml server
    

class User {
    - string name
    - string surname
    - string email
    - string hashSalt
    - string hashPass
    + void addCentral()
    + void removeCentral()
}

class Token {
    - string value
    + string getValue()
}

class Central {
    - string macAddress
    - string id
    - Config config
    + void addStation()
    + void addActuator()
}
abstract class MeshNode{
    - int id
}
class IrrigationActuator{
    - boolean status
    + boolean turnOn()
    + boolean turnOff()
}
class Config {
    - bool automatic_irrigation
}

class Station {
    - Sensor[] sensor_list
}

class Sensor {
    - int id
    - string Name
}

Central "1" o-- "1" Config : has
User "1" *-- "1" Token : uses
User "1" o-- "*" Central : owns
Central "1" o-- "*" MeshNode : connects
Station "1" *-- "*" Sensor : collects 
MeshNode <|-- Station
MeshNode <|-- IrrigationActuator
@enduml